services:
  backoffice: 
    image: danielsanchez18/gopenux-prueba-sem-ene8:latest
    environment:
      MONGO_HOST: "mongodb.docker"
      MONGO_PORT: "27017"
      MONGO_USER_FILE: /run/secrets/username_mongo
      MONGO_PASSWORD_FILE: /run/secrets/userpassword_mongo
      MONGO_DB_NAME_FILE: /run/secrets/namedb_mongo
      REDIS_HOST: "redis.docker"
      ES_HOST: "elasticsearch"
      ES_PORT: "9200"
      REDIS_PORT: "6379"
      FLASK_PORT: "5000"
      ES_INDEX: "data_index"
    ports:
      - "127.0.0.1:5000:5000"
    secrets:
      - username_mongo
      - userpassword_mongo
      - namedb_mongo
    networks:
      database:
        aliases:
          - backoffice.docker
      network-nginx:
        aliases:
          - backoffice.docker
    deploy:
      replicas: 1
      placement:
        constraints: 
          - node.labels.role == application
      resources:
        limits:
          memory: 512M
          cpus: "0.5"

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: /run/secrets/username_mongo
      MONGO_INITDB_ROOT_PASSWORD: /run/secrets/userpassword_mongo
      MONGO_INITDB_DATABASE: /run/secrets/namedb_mongo
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - /dbmongo:/data/db
    secrets:
      - username_mongo
      - userpassword_mongo
      - namedb_mongo
    networks:
      database:
        aliases:
          - mongodb.docker
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.role == database1
      resources:
        limits:
          memory: 512M
          cpus: "0.5"

  redis:
    image: redis:latest
    volumes: 
      - /local-data:/data/redis/redis-stack
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      database:
        aliases:
          - redis.docker
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.role == database2
      resources:
        limits:
          memory: 256M
          cpus: "0.25"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      database:
        aliases:
          - elasticsearch.docker
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.role == database2
      resources:
        limits:
          memory: 1.5G
          cpus: "2.0"
    ports:
      - "127.0.0.1:9200:9200"
    volumes:
      - /certs:/usr/share/elasticsearch/data

  ingress:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/ssl
    networks:
      network-nginx:
        aliases:
          - ingress.docker
    deploy:
      replicas: 1
      placement:
        constraints: 
          - node.role == manager

networks:
  database:
    driver: overlay  
  network-nginx:
    driver: overlay  

volumes:
  elasticsearch_data:

secrets:
  username_mongo:
    file: ./secrets/username_mongo.txt
  userpassword_mongo:
    file: ./secrets/userpassword_mongo.txt
  namedb_mongo:
    file: ./secrets/namedb_mongo.txt