services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false 
    ports:
      - "8080:8080" 
      - "50000:50000" 
    volumes:
      - jenkins_home:/var/jenkins_home 
    networks:
      - jenkins_network
    restart: unless-stopped

  jenkins-agent:
    image: jenkins/inbound-agent
    container_name: jenkins-agent
    environment:
      - JENKINS_URL=http://jenkins:8080 
      - AGENT_NAME=jenkins-agent 
      - JENKINS_SECRET=secret_key_from_jenkins 
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent 
    depends_on:
      - jenkins
    networks:
      - jenkins_network
    restart: unless-stopped

volumes:
  jenkins_home:
    driver: local

networks:
  jenkins_network:
    driver: bridge
